const createuser = require("./routes/createuser")
const getuser = require("./routes/getuser")
const sendmessage = require("./routes/sendmessage")
const edituser = require("./routes/edituser")
const images = require("./routes/images")
const getservers = require("./routes/getservers")
const createserver = require("./routes/createserver")
const getchannels = require("./routes/getchannels")
const deleteMessage = require("./routes/messagedelete")
const deleteServer = require("./routes/serverdelete")
const getFriendRequests = require("./routes/getfriendrequests")
const sendFriendRequest = require("./routes/sendfriendrequest")
const getFriends = require("./routes/getfriends")
const acceptFriendRequest = require("./routes/acceptfriendrequest")
const directMessage = require("./routes/directmessage")
const getdms = require("./routes/getdms")
const getServer = require("./routes/getserver")
const joinServer = require("./routes/joinserver")
const getServerMembers = require("./routes/getservermembers")

function nodeRoutes(app, io) {
    createuser(app)
    getuser(app)
    getdms(app)
    getServer(app)
    getServerMembers(app)
    directMessage(app, io)
    getFriendRequests(app)
    sendFriendRequest(app)
    acceptFriendRequest(app)
    edituser(app)
    joinServer(app)
    getFriends(app)
    sendmessage(app, io)
    images(app)
    getservers(app)
    createserver(app)
    getchannels(app)
    deleteMessage(app, io)
    deleteServer(app)
}

module.exports = nodeRoutes